<a href="https://colab.research.google.com/github/anilvce/a/blob/master/Exp_4_MatrixAnalysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import scipy.linalg as spylinalg

a = np.random.normal(5, 1, size=(4,4))
#a=np.array([1,2])
ainv = spylinalg.inv(a)
print(ainv)

[[ 1.41837222 -1.87463182  0.22843014 -0.18059195]
 [-0.22685521  2.20944718 -3.06101299  0.96310858]
 [ 0.55141178 -0.69427558  0.54570157 -0.48318058]
 [-2.09623058  0.45890915  2.94536955 -0.31466202]]


In [ ]:
print(a.dot(ainv))

[[ 1.00000000e+00 -9.58118345e-16 -1.40644813e-16  3.08037797e-16]
 [ 4.40563844e-16  1.00000000e+00 -5.22381225e-16  1.38154090e-16]
 [ 6.00829958e-16 -1.28137707e-16  1.00000000e+00 -2.96493798e-16]
 [ 5.44382921e-16 -3.77294946e-16 -1.47143817e-16  1.00000000e+00]]


In [ ]:
i4=np.eye(4)
i4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
c=a.dot(ainv)


In [ ]:
np.array_equal(c,i4)

False

In [ ]:
(c>=i4).all()

False

In [ ]:
(c>=i4).any()

True

In [ ]:
np.isclose(c,i4)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
np.allclose(c,i4)

True

In [ ]:
print(spylinalg.det(a))


46.877814293583974


In [ ]:
print(a,spylinalg.norm(a))
help(spylinalg.norm)

In [ ]:
import math
a = np.arange(9) - 4.0
print(a,spylinalg.norm(a))
math.sqrt(2*(4*4+3*3+2*2+1*1))

[-4. -3. -2. -1.  0.  1.  2.  3.  4.] 7.745966692414834


7.745966692414834

In [ ]:
print(spylinalg.norm(np.eye(4)))

2.0


In [ ]:
arect = np.random.normal(5, 1, size=(4,3))
print(spylinalg.inv(arect))

ValueError: ignored

In [ ]:
print("order=",arect.shape)
arectinv = spylinalg.pinv(arect)
print("order of inverse=",arectinv.shape)
print(arectinv)
print(arect.dot(arectinv))

order= (4, 3)
order of inverse= (3, 4)
[[-0.39799764  0.30444227 -0.26011595  0.36714797]
 [ 0.25280472 -0.20359456  0.02565415  0.019315  ]
 [ 0.14802093 -0.01802459  0.24717887 -0.293071  ]]
[[ 0.77519776 -0.22434781  0.31187804  0.16329832]
 [-0.22434781  0.7761057   0.31124759  0.16296822]
 [ 0.31187804  0.31124759  0.56731787 -0.22655095]
 [ 0.16329832  0.16296822 -0.22655095  0.88137866]]


In [ ]:
a = np.random.normal(5, 1, size=(4,4))
print(a)
print(np.trace(a))

[[5.93865977 5.51837072 4.62052817 5.94203064]
 [5.8385074  3.89774421 4.83745607 6.19888733]
 [3.69924739 4.41159784 4.71505997 3.4419113 ]
 [5.16310566 5.23583371 6.62973053 4.75143893]]
19.302902877718495


In [ ]:
b=np.array([[1,3,4],[3,2,1],[2,3,4]])
print(np.trace(b))

7


In [ ]:
np.random.randint(1,10)

9

In [ ]:
[np.random.randint(-10,10) for i in range(20)]

[-2, -8, 5, 0, 8, -4, -6, -8, 4, -5, 4, 7, -5, 6, -8, -6, 3, 8, 1, -10]

In [ ]:
x=np.array([np.random.randint(-10,10) for i in range(20)])
print(x)
print(np.mean(x))
print("exp",np.exp(x))
print("max",np.max(x))
print("argmax", np.argmax(x))

[ 6  3  9 -3  9  9 -9  9  3  7 -8 -2 -6  6  1  8  8  1  8 -2]
2.85
exp [4.03428793e+02 2.00855369e+01 8.10308393e+03 4.97870684e-02
 8.10308393e+03 8.10308393e+03 1.23409804e-04 8.10308393e+03
 2.00855369e+01 1.09663316e+03 3.35462628e-04 1.35335283e-01
 2.47875218e-03 4.03428793e+02 2.71828183e+00 2.98095799e+03
 2.98095799e+03 2.71828183e+00 2.98095799e+03 1.35335283e-01]
max 9
argmax 2


The difference between them is that the reshape() does not changes the original array but only returns the changed array, whereas the resize() method returns nothing and directly changes the original array.

In [ ]:
x.reshape(5,4)

array([[ 6,  3,  9, -3],
       [ 9,  9, -9,  9],
       [ 3,  7, -8, -2],
       [-6,  6,  1,  8],
       [ 8,  1,  8, -2]])

In [ ]:
x.resize(5,4)

In [ ]:
x

array([[ 6,  3,  9, -3],
       [ 9,  9, -9,  9],
       [ 3,  7, -8, -2],
       [-6,  6,  1,  8],
       [ 8,  1,  8, -2]])

In [ ]:
#Exercises


In [ ]:
# A  * A inverse  = A inverse * A =1
# (A.inv).inv = A
# (AB).inv = B.inv A.inv
# (A.T).inv = (A.inv).T
# inverse of (k * A) = 1/k * inverse(A)  ; k - scalar
# trace(A * A transpose)= trace(A transpose * A)
# norm(A*B) <= norm(A) * norm(B)
# pick some properties related to determinant, Trace & Rank

In [ ]:
import random
import numpy as np
marks = random.sample(range(100), 9)
a = random.sample(range(100), 9)
b = random.sample(range(100), 9)
print(marks,a)
print(type(marks))
A=np.array(a)
A.resize(3,3)
print(A)
B=np.array(b)
B.resize(3,3)
print(B)
print(A.dot(B))
AB=A.dot(B)
print("AB.T",AB.T)
BT=B.T
AT=A.T
print(BT.dot(AT))

[58, 90, 94, 32, 28, 18, 78, 47, 48] [36, 32, 67, 14, 2, 5, 83, 29, 73]
<class 'list'>
[[36 32 67]
 [14  2  5]
 [83 29 73]]
[[ 3 11 37]
 [29 97 33]
 [34 81 87]]
[[ 3314  8927  8217]
 [  270   753  1019]
 [ 3572  9639 10379]]
AB.T [[ 3314   270  3572]
 [ 8927   753  9639]
 [ 8217  1019 10379]]
[[ 3314   270  3572]
 [ 8927   753  9639]
 [ 8217  1019 10379]]
