<a href="https://colab.research.google.com/github/anilvce/a/blob/master/Exp_5_EigenVector_Matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from scipy import linalg

m = 4
n = 4

A = np.random.standard_exponential(size=(m,n))

A=np.array([[5,1],[2,3]])
print(A)
lam, V = linalg.eig(A)

print(lam)
print(V)

[[5 1]
 [2 3]]
[5.73205081+0.j 2.26794919+0.j]
[[ 0.80689822 -0.34372377]
 [ 0.59069049  0.9390708 ]]


In [ ]:
ainv=linalg.inv(A)
lam1,V1=linalg.eig(ainv)
print(lam1)
print(V1)
if (lam==lam1).all():
  print(" equal")
else:
  print("not Equal")

[-4.23606798+0.j  0.23606798+0.j]
[[-0.85065081 -0.52573111]
 [ 0.52573111 -0.85065081]]
not Equal


### EigenVector Decomposition
###### A (nonzero) vector v of dimension N is an eigenvector of a square N × N matrix A if it satisfies a linear equation of the form

###### Av  = Lambda*v

###### for some scalar λ. Then λ is called the eigenvalue corresponding to v. Geometrically speaking, the eigenvectors of A are the vectors that A merely elongates or shrinks, and the amount that they elongate/shrink by is the eigenvalue. The above equation is called the eigenvalue equation or the eigenvalue problem.

In [ ]:
print(A.dot(V))
print(lam * V )

[[ 0.20081142 -2.22703273]
 [-0.12410828 -3.60341465]]
[[ 0.20081142-0.j -2.22703273+0.j]
 [-0.12410828+0.j -3.60341465+0.j]]


In [ ]:
print(linalg.norm(A.dot(V) - lam*V))

7.260351408704585e-16


In [ ]:
# A @ V = lambda * V = V * Lambda
# A = V*lambda @ V-inv

m=n=2
lambdaMatrix = np.zeros((m, n) , dtype=complex)
lambdaInvMatrix = np.zeros((m, n), dtype=complex)
for i in range(min(m, n)):
    lambdaMatrix[i, i] = lam[i]
    lambdaInvMatrix[i, i] = 1/lam[i]

Vinv = linalg.inv(V)
print( (V.dot(lambdaMatrix)).dot(Vinv) )

print(A)

[[1.+0.j 2.+0.j]
 [2.+0.j 3.+0.j]]
[[1 2]
 [2 3]]


In [ ]:
# A = V*lambda @ V-inv
# Ainv = V * (Lambdainv) @ (V-inv)

Vinv = linalg.inv(V)
#print(Vinv)
Ainv = V.dot(lambdaInvMatrix).dot(Vinv)
print(Ainv)
Ainvd = linalg.inv(A)
print(Ainvd)

print(linalg.norm(Ainv - Ainvd))

[[-3.+0.j  2.+0.j]
 [ 2.+0.j -1.+0.j]]
[[-3.  2.]
 [ 2. -1.]]
1.9641850382783467e-15


In [ ]:
# det(A) = multipy lambda values

print("Det:\n{}".format(linalg.det(A)))
print(lam)
print(lam[0]*lam[1])
print("lambda Cumulative product:\n{}".format(lam.cumprod()) )

Det:
-1.0
[-0.23606798+0.j  4.23606798+0.j]
(-1.0000000000000004+0j)
lambda Cumulative product:
[-0.23606798+0.j -1.        +0.j]


In [ ]:
# Trace(A) = sum lambda values
print("Trace:\n{}".format(np.trace(A)))
print("lambda Cumulative sum:\n{}".format(lam.cumsum()) )

Trace:
4
lambda Cumulative sum:
[-0.23606798+0.j  4.        +0.j]


In [ ]:
D = np.array( [(1,1), (0,1)] )
print(D)
lamn, Vn = linalg.eig(D)
print(lamn)
print(Vn)
print(linalg.norm(D.dot(Vn) - lamn*Vn))

[[1 1]
 [0 1]]
[1.+0.j 1.+0.j]
[[ 1.00000000e+00 -1.00000000e+00]
 [ 0.00000000e+00  2.22044605e-16]]
2.220446049250313e-16


In [ ]:
arr=np.array([[1,1],[2,2]])
print(linalg.norm(arr))
import math
print(math.sqrt(10))

3.1622776601683795
3.1622776601683795


In [ ]:
#Exercises
#Compute eigenvectors and eigen values for any random (3,3) matrix

#compute inverse for any random matrix using Eigen factorization and verify with inv() & pinv() methods.

#Compute and compare eigenvectors and eigen values for any random (3,3) matrix and its inverse matrix - verify the results

#Compute and compare eignevectors and eigne values for any real  symmetric matrx and verify the results - eigen values are real

#Compute eignevectors and eigne values for any real symmetric matrx - check eigen vectors are othogonal

#verify matrix is not invertible if any one of its eigen value is zero.



#Read - https://towardsdatascience.com/decomposing-eigendecomposition-f68f48470830

#Exercises
#Compute eigenvectors and eigen values for any random (3,3) matrix

#compute inverse for any random matrix using Eigen factorization and verify with inv() & pinv() methods.

#Compute and compare eigenvectors and eigen values for any random (3,3) matrix and its inverse matrix - verify the results

#Compute and compare eignevectors and eigne values for any real  symmetric matrx and verify the results - eigen values are real

#Compute eignevectors and eigne values for any real symmetric matrx - check eigen vectors are othogonal

#verify matrix is not invertible if any one of its eigen value is zero.



#Read - https://towardsdatascience.com/decomposing-eigendecomposition-f68f48470830


Properties of Eigen values

The trace of A, defined as the sum of its diagonal elements,
is also the sum of all eigenvalues.

Determinant of A is the product of all its eigen values

The Eigen values of kth power of A are $λ_1^k$, $λ_2^k$, $λ_3^k$,. . . , $λ_n^k$

The matrix A is invertible if and only if every eigenvalue is nonzero.

If A is invertible, then the eigenvalues of $A^{-1}$ are $\frac{1}{λ_1}$, $\frac{1}{λ_2}$, . . . , $\frac{1}{λ_n}$

A square matrix $A$ is orthogonal if $A^T=A^{-1}$

A unitary matrix is a matrix whose inverse equals it conjugate transpose. Unitary matrices are the complex analog of real orthogonal matrices.

In mathematics, a triangular matrix is a special kind of square matrix. A square matrix is called lower triangular if all the entries above the main diagonal are zero. Similarly, a square matrix is called upper triangular if all the entries below the main diagonal are zero.

A diagonal matrix is a matrix that is both upper triangular and lower triangular. i.e., all the elements above and below the principal diagonal are zeros and hence the name "diagonal matrix". Its mathematical definition is, a matrix A = [$a_{ij}$] is said to be diagonal if

*   A is a square matrix
*   $a_{ij}$ = 0 when i ≠ j.

An identity matrix has only one eigenvalue which is 1.

The eigenvalues of triangular matrices and diagonal matrices are nothing but the elements of their principal diagonal.

A matrix and its transpose have the same eigenvalues.

If A and B are two square matrices of the same order, then AB and BA have the same eigenvalues.

The eigenvalues of an orthogonal matrix are 1 and -1.

If λ is an eigenvalue of A, then kλ is an eigenvalue of kA, where 'k' is a scalar.



  















In [ ]:
#Positive Definite Matrix - 1) symmetric, 2) all eigenvalues are positive, 3) all the subdeterminants are also positive